export type MediaStatus = "watched" | "watching" | "watchlist";

export interface Movie {
	title: string;
	year?: number;
	status: MediaStatus;
	rating?: number;
}

export interface Book {
	title: string;
	author: string;
	status: "read" | "reading" | "to-read";
	rating?: number;
}

export const MOVIES: readonly Movie[] = [
	{ title: "Inglourious Basterds", year: 2009, status: "watched", rating: 5 },
	{ title: "Pulp Fiction", year: 1994, status: "watched", rating: 5 },
	{ title: "Django Unchained", year: 2012, status: "watched", rating: 5 },
	{ title: "Mr. & Mrs. Smith", year: 2005, status: "watched", rating: 5 },
	{ title: "Snowden", year: 2016, status: "watched", rating: 4 },
	{ title: "The Lincoln Lawyer", year: 2011, status: "watched", rating: 5 },
	{ title: "Olympus Has Fallen", year: 2013, status: "watched", rating: 4 },
	{ title: "London Has Fallen", year: 2016, status: "watched", rating: 4 },
	{ title: "Angel Has Fallen", year: 2019, status: "watched", rating: 4 },
	{ title: "Carry-On", year: 2024, status: "watched", rating: 4 },
	{ title: "Heat", year: 1995, status: "watched", rating: 4 },
	{ title: "JFK", year: 1991, status: "watched", rating: 5 },
	{
		title: "All the President's Men",
		year: 1976,
		status: "watched",
		rating: 5,
	},
	{ title: "The Accountant", year: 2016, status: "watched", rating: 3 },
	{ title: "The Accountant 2", year: 2025, status: "watched", rating: 3 },
	{ title: "Red Notice", year: 2021, status: "watched", rating: 5 },
	{ title: "Den of Thieves", year: 2018, status: "watched", rating: 4 },
	{ title: "Baby Driver", year: 2017, status: "watched", rating: 4 },
	{ title: "Top Gun: Maverick", year: 2022, status: "watched", rating: 4 },
	{ title: "Oppenheimer", year: 2023, status: "watched", rating: 5 },
	{ title: "A Man Called Otto", year: 2022, status: "watched", rating: 4 },
	{
		title: "Red, White & Royal Blue",
		year: 2023,
		status: "watched",
		rating: 5,
	},
	{ title: "Catch Me If You Can", year: 2002, status: "watched", rating: 5 },
	{
		title: "The Wolf of Wall Street",
		year: 2013,
		status: "watched",
		rating: 5,
	},
	{ title: "Casino Royale", year: 2006, status: "watched", rating: 5 },
	{ title: "Quantum of Solace", year: 2008, status: "watched", rating: 4 },
	{ title: "Skyfall", year: 2012, status: "watched", rating: 5 },
	{ title: "Spectre", year: 2015, status: "watched", rating: 4 },
	{ title: "No Time to Die", year: 2021, status: "watched", rating: 5 },
	{
		title: "Mission: Impossible - Dead Reckoning",
		year: 2023,
		status: "watched",
		rating: 5,
	},
	{ title: "The Rookie", year: 2018, status: "watched", rating: 5 },
	{ title: "S.W.A.T.", year: 2017, status: "watched", rating: 3 },
	{ title: "Special Ops: Lioness", year: 2023, status: "watched", rating: 4 },
	{ title: "House M.D.", year: 2004, status: "watched", rating: 5 },
	{ title: "The Blacklist", year: 2013, status: "watched", rating: 4 },
	{ title: "The Night Agent", year: 2023, status: "watched", rating: 4 },
	{ title: "Ozark", year: 2017, status: "watched", rating: 5 },
	{ title: "The Agency", year: 2024, status: "watched", rating: 5 },
	{ title: "Money Heist", year: 2017, status: "watched", rating: 5 },
	{ title: "Money Heist: Berlin", year: 2023, status: "watched", rating: 4 },
	{ title: "Brooklyn Nine-Nine", year: 2013, status: "watched", rating: 5 },
	{ title: "Adolescence", year: 2025, status: "watched", rating: 5 },
	{ title: "Yellowstone", year: 2018, status: "watched", rating: 4 },
	{ title: "Space Force", year: 2020, status: "watched", rating: 3 },
	{ title: "Kaleidoscope", year: 2023, status: "watched", rating: 4 },
	{ title: "House of Cards", year: 2013, status: "watchlist" },
	{ title: "Lupin", year: 2021, status: "watched", rating: 5 },
	{ title: "Jack Ryan", year: 2018, status: "watched", rating: 5 },
	{ title: "The Bourne Identity", year: 2002, status: "watched", rating: 4 },
	{ title: "The Bourne Supremacy", year: 2004, status: "watched", rating: 4 },
	{ title: "The Bourne Ultimatum", year: 2007, status: "watched", rating: 4 },
	{ title: "John Wick", year: 2014, status: "watched", rating: 4 },
	{ title: "John Wick: Chapter 2", year: 2017, status: "watched", rating: 4 },
	{ title: "John Wick: Chapter 3", year: 2019, status: "watched", rating: 4 },
	{ title: "John Wick: Chapter 4", year: 2023, status: "watched", rating: 4 },
	{ title: "The Killer", year: 2023, status: "watched", rating: 4 },
	{ title: "Sicario", year: 2015, status: "watched", rating: 5 },
	{
		title: "Sicario: Day of the Soldado",
		year: 2018,
		status: "watched",
		rating: 5,
	},
	{ title: "Zero Dark Thirty", year: 2012, status: "watchlist" },
	{ title: "A Bronx Tale", year: 1993, status: "watched", rating: 5 },
	{ title: "The Hunger Games", year: 2012, status: "watched", rating: 5 },
	{
		title: "The Hunger Games: Catching Fire",
		year: 2013,
		status: "watched",
		rating: 5,
	},
	{
		title: "The Hunger Games: Mockingjay - Part 1",
		year: 2014,
		status: "watched",
		rating: 4,
	},
	{
		title: "The Hunger Games: Mockingjay - Part 2",
		year: 2015,
		status: "watched",
		rating: 4,
	},
	{
		title: "The Hunger Games: The Ballad of Songbirds & Snakes",
		year: 2023,
		status: "watched",
		rating: 5,
	},
	{ title: "The Social Network", year: 2010, status: "watched", rating: 4 },
	{ title: "The Da Vinci Code", year: 2006, status: "watched", rating: 4 },
	{ title: "Ocean's Eleven", year: 2001, status: "watched", rating: 5 },
	{ title: "Ocean's Twelve", year: 2004, status: "watched", rating: 4 },
	{ title: "Ocean's Thirteen", year: 2007, status: "watched", rating: 4 },
	{
		title: "The Shawshank Redemption",
		year: 1994,
		status: "watched",
		rating: 5,
	},
	{ title: "Jack Reacher", year: 2012, status: "watched", rating: 4 },
	{
		title: "Jack Reacher: Never Go Back",
		year: 2016,
		status: "watched",
		rating: 4,
	},
	{ title: "Reacher", year: 2022, status: "watched", rating: 4 },
	{ title: "Die Hard", year: 1988, status: "watched", rating: 5 },
	{ title: "Die Hard 2", year: 1990, status: "watched", rating: 4 },
	{
		title: "Die Hard with a Vengeance",
		year: 1995,
		status: "watched",
		rating: 5,
	},
	{ title: "Live Free or Die Hard", year: 2007, status: "watched", rating: 4 },
	{ title: "A Good Day to Die Hard", year: 2013, status: "watched", rating: 3 },
	{ title: "Whiplash", year: 2014, status: "watched", rating: 4 },
	{ title: "Now You See Me 2", year: 2016, status: "watched", rating: 3 },
	{ title: "The Dictator", year: 2012, status: "watched", rating: 5 },
	{ title: "Taxi", year: 2004, status: "watched", rating: 3 },
	{ title: "Lift", year: 2024, status: "watched", rating: 5 },
	{
		title: "Star Wars: Episode IV - A New Hope",
		year: 1977,
		status: "watched",
		rating: 5,
	},
	{
		title: "Star Wars: Episode V - The Empire Strikes Back",
		year: 1980,
		status: "watched",
		rating: 5,
	},
	{
		title: "Star Wars: Episode VI - Return of the Jedi",
		year: 1983,
		status: "watched",
		rating: 4,
	},
	{
		title: "Star Wars: Episode I - The Phantom Menace",
		year: 1999,
		status: "watched",
		rating: 3,
	},
	{
		title: "Star Wars: Episode II - Attack of the Clones",
		year: 2002,
		status: "watched",
		rating: 3,
	},
	{
		title: "Star Wars: Episode III - Revenge of the Sith",
		year: 2005,
		status: "watched",
		rating: 4,
	},
	{
		title: "Star Wars: Episode VII - The Force Awakens",
		year: 2015,
		status: "watched",
		rating: 4,
	},
	{ title: "Dune", year: 2021, status: "watched", rating: 4 },
	{ title: "Dune: Part Two", year: 2024, status: "watched", rating: 4 },
	{ title: "A House of Dynamite", year: 2025, status: "watched", rating: 5 },
	{ title: "F1", year: 2025, status: "watched", rating: 5 },
	{ title: "Narcos", year: 2015, status: "watching" },
	{ title: "Victoria and Abdul", year: 2017, status: "watchlist" },
	{ title: "1984", year: 1984, status: "watched", rating: 5 },
	{ title: "Family Plan 2", year: 2025, status: "watched", rating: 5 },
	{ title: "Shooter", year: 2007, status: "watchlist" },
	{ title: "The Godfather", year: 1972, status: "watched", rating: 4 },
	{ title: "The Godfather Part II", year: 1974, status: "watched", rating: 4 },
] as const;

export const BOOKS: readonly Book[] = [
	{ title: "Steve Jobs", author: "Walter Isaacson", status: "read", rating: 4 },
	{ title: "V for Vendetta", author: "Alan Moore", status: "read", rating: 5 },
	{ title: "L'Étranger", author: "Albert Camus", status: "read", rating: 5 },
	{
		title: "Macbeth",
		author: "William Shakespeare",
		status: "read",
		rating: 3,
	},
	{
		title: "Ils étaient dix",
		author: "Agatha Christie",
		status: "read",
		rating: 5,
	},
	{
		title: "The Midnight Library",
		author: "Matt Haig",
		status: "read",
		rating: 4,
	},
	{
		title: "Murder on the Orient Express",
		author: "Agatha Christie",
		status: "read",
		rating: 4,
	},
	{
		title: "The Hunger Games",
		author: "Suzanne Collins",
		status: "read",
		rating: 5,
	},
	{
		title: "Catching Fire",
		author: "Suzanne Collins",
		status: "read",
		rating: 5,
	},
	{ title: "Mockingjay", author: "Suzanne Collins", status: "read", rating: 5 },
	{
		title: "The Ballad of Songbirds and Snakes",
		author: "Suzanne Collins",
		status: "read",
		rating: 5,
	},
	{
		title: "Harry Potter Series",
		author: "J.K. Rowling",
		status: "read",
		rating: 4,
	},
	{
		title: "Percy Jackson Series",
		author: "Rick Riordan",
		status: "read",
		rating: 3,
	},
	{ title: "The Art of War", author: "Sun Tzu", status: "read", rating: 4 },
	{ title: "To Kill a Mockingbird", author: "Harper Lee", status: "reading" },
	{ title: "Ghost Wars", author: "Steve Coll", status: "to-read" },
	{ title: "Diplomacy", author: "Henry Kissinger", status: "to-read" },
	{
		title: "The Motorcycle Diaries",
		author: "Ernesto Che Guevara",
		status: "to-read",
	},
	{ title: "1984", author: "George Orwell", status: "read", rating: 5 },
	{ title: "Bad Company", author: "Jack Higgins", status: "read", rating: 4 },
	{
		title: "What They Don't Teach You at Harvard Business School",
		author: "Mark H. McCormack",
		status: "read",
		rating: 4,
	},
	{
		title: "The Power of Speech",
		author: "Marie Stuttard",
		status: "read",
		rating: 3,
	},
	{
		title: "The Da Vinci Code",
		author: "Dan Brown",
		status: "read",
		rating: 4,
	},
	{ title: "The Hobbit", author: "J.R.R. Tolkien", status: "read", rating: 2 },
	{
		title: "La Planète des singes",
		author: "Pierre Boulle",
		status: "read",
		rating: 4,
	},
	{
		title: "Le meurtre de Roger Ackroyd",
		author: "Agatha Christie",
		status: "read",
		rating: 5,
	},
	{ title: "Deception Point", author: "Dan Brown", status: "read", rating: 4 },
	{ title: "Maus", author: "Art Spiegelman", status: "read", rating: 4 },
	{
		title: "Le programme",
		author: "Sandra Dussault",
		status: "read",
		rating: 4,
	},
	{ title: "Why We Buy", author: "Paco Underhill", status: "read", rating: 4 },
	{ title: "Brave New World", author: "Aldous Huxley", status: "to-read" },
	{ title: "Neuromancer", author: "William Gibson", status: "to-read" },
	{ title: "Jennifer Government", author: "Max Barry", status: "to-read" },
	{ title: "Blindness", author: "José Saramago", status: "to-read" },
	{ title: "Everyone in Silico", author: "Jim Munroe", status: "to-read" },
	{ title: "Animal Farm", author: "George Orwell", status: "to-read" },
	{
		title: "Down and Out in Paris and London",
		author: "George Orwell",
		status: "to-read",
	},
	{
		title: "The Road to Wigan Pier",
		author: "George Orwell",
		status: "to-read",
	},
	{ title: "Fahrenheit 451", author: "Ray Bradbury", status: "to-read" },
	{ title: "On Bullshit", author: "Harry G. Frankfurt", status: "to-read" },
	{
		title: "Reluctant Spy: My Secret Life in the CIA's War on Terror",
		author: "John Kiriakou",
		status: "to-read",
	},
] as const;
